name: CI

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.org'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: git config
        run: git config --global core.autocrlf false
        shell: bash
      - name: setup msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
      - uses: actions/checkout@v4
      - name: build
        shell: msys2 {0}
        run: |
          chmod +x build-emacs.sh
          ./build-emacs.sh
          cd /c/emacs/emacs-master
          echo "EMACS_VER=`date  +'%Y%m%d'`_`git rev-parse --short HEAD`" >> $GITHUB_ENV
      - name: release
        uses: softprops/action-gh-release@v2
        with:
          name: emacs_${{ env.EMACS_VER }}
          tag_name: ${{ env.EMACS_VER }}
          files: C:/programs/emacs-*.tar.gz
