name: release

on:
  push:
    tags:
      - "emacs-*"

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: git config
        run: git config --global core.autocrlf false
        shell: bash
      - name: setup msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
      - uses: actions/checkout@v4
      - name: build
        shell: msys2 {0}
        run: |
          chmod +x build-emacs.sh
          ./build-emacs.sh ${{ github.ref_name }}
          cd /c/emacs/emacs-repo
          echo "EMACS_VER=`date  +'%Y%m%d'`-`git rev-parse --short HEAD`" >> $GITHUB_ENV
          cd /c/programs/
          mv emacs.tar.gz ${{ github.ref_name }}.tar.gz
      - name: release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body: "${{ github.ref_name }}-${{ env.EMACS_VER }}"
          draft: false
          prerelease: false
          files: C:/programs/emacs-*.tar.gz
